AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer in front of Docker Swarm manager

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC där Swarm-klustret ligger

  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Publikt subnet 1 (AZ A)

  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Publikt subnet 2 (AZ B)

  ManagerInstanceId:
    Type: String
    Description: EC2 InstanceId för Swarm-manager (från första stacken)

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from internet to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-alb-sg"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AWS::StackName}-tg"
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      Matcher:
        HttpCode: "200"
      Targets:
        - Id: !Ref ManagerInstanceId
          Port: 80

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-alb"
      Scheme: internet-facing
      Type: application
      SecurityGroups: [ !Ref AlbSecurityGroup ]
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      IpAddressType: ipv4
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-alb"

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  AlbDnsName:
    Description: DNS-namn för ALB
    Value: !GetAtt LoadBalancer.DNSName
